/-
Copyright (c) 2025 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.CategoryTheory.Elements
public import TopCatModelCategory.SSet.StandardSimplex

/-!
# The type of simplices of a simplicial set

In this file, we define the type `X.S` of simplices of a simplicial set `X`,
where a simplex consists of the data of `dim : ℕ` and `simplex : X _⦋dim⦌`.
We endow this type with a preorder defined by
`x ≤ y ↔ Subcomplex.ofSimplex x.simplex ≤ Subcomplex.ofSimplex y.simplex`.

## TODO (@joelriou)

* Extend the `S` structure to define the type of nondegenerate
simplices of a simplicial set `X`, and also the type of nondegenerate
simplices of a simplicial set `X` which do not belong to a given subcomplex.

-/

@[expose] public section

universe u

open CategoryTheory Simplicial Opposite

namespace SSet

variable {X : SSet.{u}}

@[simp]
lemma Subcomplex.ofSimplex_map {n m : ℕ} (f : ⦋n⦌ ⟶ ⦋m⦌) [Epi f]
    (x : X _⦋m⦌) :
    ofSimplex (X.map f.op x) = ofSimplex x := by
  apply le_antisymm
  · rw [Subpresheaf.ofSection_le_iff]
    exact ⟨_, rfl⟩
  · rw [Subpresheaf.ofSection_le_iff]
    have := isSplitEpi_of_epi f
    exact ⟨(section_ f).op, by
      rw [← FunctorToTypes.map_comp_apply, ← op_comp,
        IsSplitEpi.id, op_id, FunctorToTypes.map_id_apply]⟩

variable (X) in
/-- The type of simplices of a simpliciat set `X`. -/
structure S where
  /-- the dimension of the simplex -/
  {dim : ℕ}
  /-- the simplex -/
  simplex : X _⦋dim⦌

namespace S

@[simp]
lemma mk_simplex (s : X.S) : S.mk s.simplex = s := rfl

lemma mk_surjective (s : X.S) :
    ∃ (n : ℕ) (x : X _⦋n⦌), s = mk x :=
  ⟨s.1, s.2, rfl⟩

@[simps!]
def toSubcomplex (x : X.S) {A : X.Subcomplex} (hx : x.simplex ∈ A.obj _) : A.toSSet.S :=
  S.mk ⟨x.simplex, hx⟩

/-- The image of a simplex by a morphism of simplicial sets. -/
@[simps]
def map {Y : SSet.{u}} (f : X ⟶ Y) (s : X.S) : Y.S :=
  S.mk (f.app _ s.2)

@[simp]
lemma map_toSubcomplex (x : X.S) {A : X.Subcomplex} (hx : x.simplex ∈ A.obj _) :
    S.map A.ι (x.toSubcomplex hx) = x := rfl

lemma simplex_map_nonDegenerate_iff_of_mono {Y : SSet.{u}} (f : X ⟶ Y) [Mono f] (s : X.S) :
    (S.map f s).simplex ∈ Y.nonDegenerate _ ↔ s.simplex ∈ X.nonDegenerate _ := by
  simp [S.map, nonDegenerate_iff_of_mono]

@[simp]
lemma map_id (s : X.S) : S.map (𝟙 _) s = s := rfl

lemma map_map {Y Z : SSet.{u}} (f : X ⟶ Y) (g : Y ⟶ Z) (s : X.S) :
    S.map g (S.map f s) = S.map (f ≫ g) s := rfl

lemma dim_eq_of_eq {s t : X.S} (h : s = t) :
    s.dim = t.dim :=
  congr_arg dim h

lemma dim_eq_of_mk_eq {n m : ℕ} {x : X _⦋n⦌} {y : X _⦋m⦌}
    (h : S.mk x = S.mk y) : n = m :=
  dim_eq_of_eq h

section

variable (s : X.S) {d : ℕ} (hd : s.dim = d)

/-- When `s : X.S` is such that `s.dim = d`, this is a term
that is equal to `s`, but whose dimension if definitionally equal to `d`. -/
@[simps dim]
def cast : X.S where
  dim := d
  simplex := _root_.cast (by simp only [hd]) s.simplex

lemma cast_eq_self : s.cast hd = s := by
  obtain ⟨d, _, rfl⟩ := s.mk_surjective
  obtain rfl := hd
  rfl

@[simp]
lemma cast_simplex_rfl : (s.cast rfl).simplex = s.simplex := rfl

end

lemma ext_iff' (s t : X.S) :
    s = t ↔ ∃ (h : s.dim = t.dim), (s.cast h).2 = t.2 :=
  ⟨by rintro rfl; exact ⟨rfl, rfl⟩, fun ⟨h₁, h₂⟩ ↦ by
    obtain ⟨_, _, rfl⟩ := s.mk_surjective
    obtain ⟨_, _, rfl⟩ := t.mk_surjective
    aesop⟩

lemma ext_iff {n : ℕ} (x y : X _⦋n⦌) :
    S.mk x = S.mk y ↔ x = y := by
  simp

lemma map_injective_of_mono {Y : SSet.{u}} (f : X ⟶ Y) [Mono f] :
    Function.Injective (S.map f) := by
  intro x y h
  obtain ⟨d, x, rfl⟩ := x.mk_surjective
  obtain ⟨d', y, rfl⟩ := y.mk_surjective
  obtain rfl := S.dim_eq_of_mk_eq h
  simp only [ext_iff', map_dim, cast_dim, cast_simplex_rfl, map_simplex, exists_const] at h
  rw [ext_iff]
  exact (mono_iff_injective _).1 inferInstance h

instance : Preorder X.S where
  le x y := Subcomplex.ofSimplex x.2 ≤ Subcomplex.ofSimplex y.2
  le_refl _ := le_refl (α := Subcomplex X) _
  le_trans _ _ _ := le_trans (α := Subcomplex X)

-- The subcomplex generated by a simplex. -/
abbrev subcomplex (x : X.S) : X.Subcomplex := Subcomplex.ofSimplex x.2

lemma le_iff {x y : X.S} : x ≤ y ↔ x.subcomplex ≤ y.subcomplex :=
  Iff.rfl

lemma mk_map_le {n m : ℕ} (x : X _⦋n⦌) (f : ⦋m⦌ ⟶ ⦋n⦌) :
    S.mk (X.map f.op x) ≤ S.mk x := by
  rw [le_iff, Subcomplex.ofSimplex_le_iff]
  exact ⟨f.op, rfl⟩

lemma mk_map_eq_iff_of_mono {n m : ℕ} (x : X _⦋n⦌)
    (f : ⦋m⦌ ⟶ ⦋n⦌) [Mono f] :
    S.mk (X.map f.op x) = S.mk x ↔ IsIso f := by
  constructor
  · intro h
    obtain rfl := S.dim_eq_of_mk_eq h
    obtain rfl := SimplexCategory.eq_id_of_mono f
    infer_instance
  · intro hf
    obtain rfl : n = m :=
      le_antisymm
        (SimplexCategory.len_le_of_epi f)
        (SimplexCategory.len_le_of_mono f)
    obtain rfl := SimplexCategory.eq_id_of_isIso f
    simp

/-- The type of simplices of `X : SSet.{u}` identifies to the type
of elements of `X` considered as a functor `SimplexCategoryᵒᵖ ⥤ Type u`. -/
@[simps!]
def equivElements : X.S ≃ X.Elements where
  toFun s := X.elementsMk _ s.2
  invFun := by
    rintro ⟨⟨n⟩, x⟩
    induction n using SimplexCategory.rec
    exact S.mk x
  left_inv _ := rfl
  right_inv _ := rfl

@[simp]
lemma subcomplex_map {Y : SSet.{u}} (f : X ⟶ Y) (x : X.S) :
    (S.map f x).subcomplex = x.subcomplex.image f := by
  simp [subcomplex]

lemma toSubcomplex_le_toSubcomplex_iff
    (x y : X.S) {A : X.Subcomplex} (hx : x.simplex ∈ A.obj _) (hy : y.simplex ∈ A.obj _) :
    x.toSubcomplex hx ≤ y.toSubcomplex hy ↔ x ≤ y := by
  simp only [le_iff, Subpresheaf.ofSection_le_iff]
  constructor
  · rintro ⟨f, hf⟩
    exact ⟨f, by rwa [Subtype.ext_iff] at hf⟩
  · rintro ⟨f, hf⟩
    exact ⟨f, by rwa [Subtype.ext_iff]⟩

@[simp]
lemma map_ι_toSubcomplex (x : X.S) {A : X.Subcomplex} (hx : x.simplex ∈ A.obj _) :
  S.map A.ι (x.toSubcomplex hx) = x := rfl

end S

end SSet
