module

public import Mathlib.AlgebraicTopology.RelativeCellComplex.Basic
public import Mathlib.CategoryTheory.Limits.Lattice
public import TopCatModelCategory.SSet.Degenerate
public import TopCatModelCategory.SSet.Evaluation
public import TopCatModelCategory.SSet.Monomorphisms
public import TopCatModelCategory.SSet.NonDegenerateSimplices
public import TopCatModelCategory.ColimitsType

@[expose] public section

open CategoryTheory Simplicial HomotopicalAlgebra Limits Opposite

namespace SSet

lemma mono_of_nonDegenerate' {X : SSet.{u}} {d d' : ℕ} (x : X _⦋d⦌)
    (f : ⦋d'⦌ ⟶ ⦋d⦌)
    (h : X.map f.op x ∈ X.nonDegenerate d') : Mono f := by
  have := isIso_of_nonDegenerate _ ⟨_, h⟩ (factorThruImage f)
    (X.map (image.ι f).op x) (by
      rw [← FunctorToTypes.map_comp_apply, ← op_comp, image.fac])
  rw [← image.fac f]
  infer_instance

variable (X : SSet.{u})

/-- `X.skeleton n` is the subcomplex of `X` generated by (non degenerate)
simplices of dimension `< n`. -/
def skeleton : ℕ →o X.Subcomplex where
  toFun n := ⨆ (i : Fin n) (x : X.nonDegenerate i), Subcomplex.ofSimplex x.1
  monotone' i j h := by
    simp only [iSup_le_iff]
    intro k x
    exact le_trans (by exact le_trans (by rfl) (le_iSup _ x))
      (le_iSup _ ⟨k, by omega⟩)

lemma mem_skeleton {i : ℕ} (x : X _⦋i⦌) {n : ℕ} (hi : i < n) :
    x ∈ (X.skeleton n).obj _ := by
  obtain ⟨j, f, _, y, rfl⟩ := X.exists_nonDegenerate x
  suffices Subcomplex.ofSimplex y.1 ≤ X.skeleton n from
    (X.skeleton n).map _ (this _ (Subcomplex.mem_ofSimplex_obj _))
  exact le_trans (by exact le_trans (by rfl) (le_iSup _ y))
    (le_iSup _ ⟨j, lt_of_le_of_lt
      (SimplexCategory.len_le_of_epi f) hi⟩)

lemma skeleton_obj_eq_top {d n : ℕ} (h : d < n) :
    (X.skeleton n).obj (op ⦋d⦌) = ⊤ := by
  rw [← top_le_iff]
  intro x _
  exact mem_skeleton _ _ h

lemma ofSimplex_le_skeleton {i : ℕ} (x : X _⦋i⦌) {n : ℕ} (hi : i < n) :
    Subcomplex.ofSimplex x ≤ X.skeleton n := by
  simpa using X.mem_skeleton x hi

lemma mem_skeleton_obj_iff_of_nonDegenerate
    {d : ℕ} (x : X.nonDegenerate d) (n : ℕ) :
    x.1 ∈ (X.skeleton n).obj _ ↔ d < n := by
  constructor
  · intro h
    simp [skeleton] at h
    obtain ⟨x, hx⟩ := x
    obtain ⟨⟨i, hi⟩, y, hy, ⟨f⟩, rfl⟩ := h
    dsimp at y hy f
    have := mono_of_nonDegenerate' y f hx
    have : d ≤ i := SimplexCategory.len_le_of_mono f
    omega
  · apply mem_skeleton

@[simp]
lemma skeleton_zero : X.skeleton 0 = ⊥ := by
  simp [skeleton]

lemma iSup_skeleton : ⨆ (n : ℕ), X.skeleton n = ⊤ := by
  apply le_antisymm (by simp)
  rw [Subcomplex.le_iff_contains_nonDegenerate]
  intro n x _
  simp only [Subpresheaf.iSup_obj, Set.mem_iUnion]
  exact ⟨n + 1, mem_skeleton _ _ (by omega)⟩

lemma skeleton_succ (n : ℕ) :
    X.skeleton (n + 1) =
      X.skeleton n ⊔ ⨆ (x : X.nonDegenerate n), Subcomplex.ofSimplex x.1 := by
  apply le_antisymm
  · conv_lhs => dsimp [skeleton]
    simp only [iSup_le_iff]
    rintro ⟨d, hd⟩ x
    rw [Nat.lt_succ_iff] at hd
    obtain hd | rfl := hd.lt_or_eq
    · exact (X.ofSimplex_le_skeleton _ hd).trans le_sup_left
    · exact le_trans (le_trans (by rfl) (le_iSup _ x)) le_sup_right
  · simp only [sup_le_iff, iSup_le_iff]
    constructor
    · exact X.skeleton.monotone (by simp)
    · intro x
      apply X.ofSimplex_le_skeleton _ (by simp)

variable {X} {Y : SSet.{u}} (i : X ⟶ Y)

def skeletonOfMono [Mono i] : ℕ →o Y.Subcomplex where
  toFun n := Subcomplex.range i ⊔ Y.skeleton n
  monotone' n m h := by
    dsimp
    simp only [sup_le_iff, le_sup_left, true_and]
    exact le_trans (Y.skeleton.monotone h) le_sup_right

section

variable [Mono i]

lemma skeleton_le_skeletonOfMono (n : ℕ) :
    Y.skeleton n ≤ skeletonOfMono i n := le_sup_right

@[simp]
lemma skeletonOfMono_zero : skeletonOfMono i 0 = Subcomplex.range i := by
  simp [skeletonOfMono]

lemma iSup_skeletonOfMono : ⨆ (n : ℕ), skeletonOfMono i n = ⊤ := by
  apply le_antisymm (by simp)
  rw [← Y.iSup_skeleton, iSup_le_iff]
  intro n
  exact le_trans (skeleton_le_skeletonOfMono i n) (le_iSup _ n)

lemma mem_skeletonOfMono_obj_iff_of_nonDegenerate
    {d : ℕ} (x : Y.nonDegenerate d) (n : ℕ) :
    x.1 ∈ (skeletonOfMono i n).obj _ ↔
      x.1 ∈ Set.range (i.app _) ∨ d < n := by
  simp [skeletonOfMono, mem_skeleton_obj_iff_of_nonDegenerate]

lemma skeletonOfMono_obj_eq_top {d n : ℕ} (h : d < n) :
    (skeletonOfMono i n).obj (op ⦋d⦌) = ⊤ := by
  rw [← top_le_iff, ← Y.skeleton_obj_eq_top h]
  exact le_sup_right

lemma skeletonOfMono_succ (n : ℕ) :
    skeletonOfMono i (n + 1) =
      skeletonOfMono i n ⊔ ⨆ (x : Y.nonDegenerate n)
        (_ : x.1 ∉ (Subcomplex.range i).obj _), Subcomplex.ofSimplex x.1 := by
  dsimp only [skeletonOfMono, OrderHom.coe_mk]
  apply le_antisymm
  · simp only [sup_le_iff, iSup_le_iff, skeleton_succ]
    refine ⟨le_sup_left.trans le_sup_left,
      le_sup_right.trans le_sup_left, fun x ↦ ?_⟩
    by_cases hx : x.1 ∈ (Subcomplex.range i).obj _
    · exact le_trans (le_trans (by simpa) le_sup_left) le_sup_left
    · exact (le_trans (by exact le_trans (by rfl) (le_iSup _ hx))
        (le_iSup _ x)).trans le_sup_right
  · simp only [sup_le_iff, iSup_le_iff]
    exact ⟨⟨le_sup_left, (Y.skeleton.monotone (by simp)).trans le_sup_right⟩,
      fun _ _ ↦ (Y.ofSimplex_le_skeleton _ (by simp)).trans le_sup_right⟩

end

namespace relativeCellComplexOfMono

variable (d : ℕ)

def ι [Mono i] : Type u :=
  { y : Y.nonDegenerate d // y.1 ∉ (Subcomplex.range i).obj _ }

variable [Mono i]

noncomputable def A : SSet.{u} := ∐ (fun (_ : ι i d) ↦ boundary d)

noncomputable def B : SSet.{u} := ∐ (fun (_ : ι i d) ↦ Δ[d])

variable {i d}

noncomputable def ιA (x : ι i d) : (boundary d : SSet) ⟶ A i d :=
  Limits.Sigma.ι (fun _ ↦ _) x

noncomputable def ιB (x : ι i d) : Δ[d] ⟶ B i d :=
  Limits.Sigma.ι (fun _ ↦ _) x

lemma ιA_jointly_surjective {n : ℕ} (a : (A i d) _⦋n⦌) :
    ∃ (x : ι i d) (a' : (∂Δ[d] : SSet) _⦋n⦌), (ιA x).app _ a' = a :=
  Types.jointly_surjective_of_isColimit_cofan
    (isColimitCofanMkObjOfIsColimit ((evaluation _ _).obj (op ⦋n⦌)) _ _
    (coproductIsCoproduct _)) a

lemma ιB_jointly_surjective {n : ℕ} (b : (B i d) _⦋n⦌) :
    ∃ (x : ι i d) (b' : Δ[d] _⦋n⦌), (ιB x).app _ b' = b :=
  Types.jointly_surjective_of_isColimit_cofan
    (isColimitCofanMkObjOfIsColimit ((evaluation _ _).obj (op ⦋n⦌)) _ _
    (coproductIsCoproduct _)) b

variable (i d) in
noncomputable def m : A i d ⟶ B i d := Limits.Sigma.map (fun _ ↦ (boundary d).ι)

instance : Mono (m i d) := by
  dsimp [m]
  infer_instance

@[reassoc (attr := simp)]
lemma ιA_m (x : ι i d) : ιA x ≫ m i d = (boundary d).ι ≫ ιB x := by
  simp [m, ιA, ιB]

lemma mem_skeletonOfMono (x : ι i d) {d' : ℕ} (h : d < d') :
    x.1.1 ∈ (skeletonOfMono i d').obj _ := by
  simp only [skeletonOfMono, OrderHom.coe_mk, Subpresheaf.max_obj, Set.mem_union]
  exact Or.inr (Y.mem_skeleton _ h)

def β (x : ι i d) : Δ[d] ⟶ skeletonOfMono i (d + 1) :=
  yonedaEquiv.symm ⟨x.1.1, mem_skeletonOfMono x (by simp)⟩

variable (i d) in
noncomputable def b : B i d ⟶ skeletonOfMono i (d + 1) := Sigma.desc β

@[reassoc (attr := simp)]
lemma ιB_b (x : ι i d) : ιB x ≫ b i d = β x := by simp [ιB, b]

lemma preimage_skeletonOfMono_eq (x : ι i d) :
    (skeletonOfMono i d).preimage (yonedaEquiv.symm x.1.1) = ∂Δ[d] := by
  rw [stdSimplex.eq_boundary_iff]
  constructor
  · rw [Subcomplex.le_iff_contains_nonDegenerate]
    rintro n ⟨y, hy₁⟩ hy₂
    have : n < d := dim_lt_of_nondegenerate (X := ∂Δ[d])
      (⟨⟨y, hy₂⟩, by rwa [Subcomplex.mem_nonDegenerate_iff]⟩) d
    simp [skeletonOfMono_obj_eq_top i this]
  · intro h
    have := h.symm.le _ (show stdSimplex.objEquiv.symm (𝟙 ⦋d⦌)  ∈ _ by simp)
    simp only [Subpresheaf.range_obj, Subcomplex.preimage_obj, Set.mem_preimage] at this
    change Y.map (𝟙 _) x.1.1 ∈ (skeletonOfMono i d).obj _ at this
    simp only [Subpresheaf.range_obj, FunctorToTypes.map_id_apply,
      mem_skeletonOfMono_obj_iff_of_nonDegenerate, Set.mem_range, lt_self_iff_false,
      or_false] at this
    exact x.2 this

def τ (x : ι i d) : (∂Δ[d] : SSet) ⟶ skeletonOfMono i d :=
  Subcomplex.lift (∂Δ[d].ι ≫ yonedaEquiv.symm x.1.1) (by
    rw [Subcomplex.preimage_preimage, preimage_skeletonOfMono_eq,
      Subcomplex.preimage_ι])

@[simp]
lemma τ_app_coe (x : ι i d) {n : ℕ} (a : (∂Δ[d] : SSet) _⦋n⦌) :
    ((τ x).app _ a).1 = (β x).app _ a.1 := rfl

variable (i d) in
noncomputable def t : A i d ⟶ skeletonOfMono i d := Sigma.desc τ

@[reassoc (attr := simp)]
lemma ιA_t (x : ι i d) : ιA x ≫ t i d = τ x := by simp [ιA, t]

variable (i d) in
def r : (skeletonOfMono i d : SSet) ⟶ skeletonOfMono i (d + 1) :=
  Subcomplex.homOfLE ((skeletonOfMono i).monotone (by simp))

variable (i d) in
instance mono_r : Mono (r i d) := by dsimp [r]; infer_instance

@[reassoc]
lemma τ_r (x : ι i d) : τ x ≫ r i d = ∂Δ[d].ι ≫ β x := rfl

@[simp]
lemma r_app_coe {n : ℕ} (y : (skeletonOfMono i d : SSet) _⦋n⦌) :
    ((r i d).app _ y).1 = y.1 := rfl

variable (i d)

@[reassoc]
lemma w : t i d ≫ r i d = m i d ≫ b i d :=
  Sigma.hom_ext _ _ (fun x ↦ by
    change ιA x ≫ t i d ≫ r i d = ιA x ≫ m i d ≫ b i d
    simp [τ_r])

lemma sup_range_r_range_b :
    Subcomplex.range (r i d) ⊔ Subcomplex.range (b i d) = ⊤ := by
  rw [← top_le_iff]
  rintro n ⟨x, hx⟩ _
  simp only [skeletonOfMono_succ, Subpresheaf.range_obj, Set.mem_range, not_exists,
    Subpresheaf.max_obj, Subpresheaf.iSup_obj, Subcomplex.iSup_obj, Set.iUnion_coe_set,
    Set.mem_union, Set.mem_iUnion, exists_prop] at hx
  simp only [Subpresheaf.toPresheaf_obj, Subpresheaf.max_obj, Subpresheaf.range_obj, Set.mem_union,
    Set.mem_range, Subtype.exists]
  obtain hx | ⟨y, hy₁, hy₂, ⟨f⟩, rfl⟩  := hx
  · exact Or.inl ⟨x, hx, rfl⟩
  · refine Or.inr ⟨(ιB ⟨⟨y, hy₁⟩, by simpa⟩).app _
      (stdSimplex.objEquiv.symm f), ?_⟩
    rw [← FunctorToTypes.comp, ιB_b]
    rfl

lemma range_r_app_union_range_b_app (n : SimplexCategoryᵒᵖ) :
    Set.range ((r i d).app n) ∪
      Set.range ((b i d).app n) = Set.univ :=
  congr_fun (congr_arg Subpresheaf.obj (sup_range_r_range_b i d)) n

lemma isPullback : IsPullback (t i d) (m i d) (r i d) (b i d) where
  w := w i d
  isLimit' := ⟨evaluationJointlyReflectsLimits _ (fun ⟨n⟩ ↦ by
    refine (isLimitMapConePullbackConeEquiv _ _).2
      (IsPullback.isLimit ?_)
    induction n using SimplexCategory.rec with | _ n
    rw [Types.isPullback_iff]
    dsimp
    refine ⟨?_, ?_, ?_⟩
    · exact (congr_app (w i d) (op ⦋n⦌))
    · intro a₁ a₂ ⟨ht, hm⟩
      have : Mono (m i d) := inferInstance
      rw [NatTrans.mono_iff_mono_app] at this
      simp only [mono_iff_injective] at this
      exact this _ hm
    · intro y b h
      obtain ⟨x, b, rfl⟩ := ιB_jointly_surjective b
      have hb : b ∈ ∂Δ[d].obj _ := by
        obtain ⟨y, hy⟩ := y
        rw [← preimage_skeletonOfMono_eq x]
        rw [Subtype.ext_iff] at h
        dsimp at h
        subst h
        rwa [← FunctorToTypes.comp, ιB_b] at hy
      refine ⟨(ιA x).app _ ⟨b, hb⟩, ?_, ?_⟩
      · rw [Subtype.ext_iff] at h
        dsimp at h
        rw [← FunctorToTypes.comp, ιA_t]
        rw [← FunctorToTypes.comp, ιB_b] at h
        ext
        exact h
      · rw [← FunctorToTypes.comp, ιA_m, comp_app, types_comp_apply,
          Subpresheaf.ι_app])⟩


variable {i d} in
lemma exists_epi {n : ℕ} (y : (B i d) _⦋n⦌)
    (hy : y ∉ Set.range ((m i d).app (op ⦋n⦌))) :
    ∃ (x : ι i d) (f : ⦋n⦌ ⟶ ⦋d⦌) (_ : Epi f),
    (ιB x).app (op ⦋n⦌) (stdSimplex.objEquiv.symm f) = y := by
  obtain ⟨x, s, rfl⟩ := ιB_jointly_surjective y
  have hs : s ∉ ∂Δ[d].obj _ := fun hs ↦ hy (⟨(ιA x).app _ ⟨s, hs⟩, by
    rw [← FunctorToTypes.comp, ιA_m, comp_app, types_comp_apply, Subpresheaf.ι_app]⟩)
  refine ⟨x, stdSimplex.objEquiv (m := op ⦋n⦌) s,
    by simpa [SimplexCategory.epi_iff_surjective, boundary] using hs,
    by simp⟩

lemma isPushout : IsPushout (t i d) (m i d) (r i d) (b i d) where
  w := w i d
  isColimit' := ⟨evaluationJointlyReflectsColimits _ (fun ⟨n⟩ ↦ by
    induction n using SimplexCategory.rec with | _ n
    refine (isColimitMapCoconePushoutCoconeEquiv _ _).2
      (IsPushout.isColimit ?_)
    have := mono_r i d
    refine Limits.Types.isPushout_of_isPullback_of_mono' ?_ ?_ ?_
    · exact (isPullback i d).map ((evaluation _ _).obj (op ⦋n⦌))
    · exact range_r_app_union_range_b_app _ _ _
    · dsimp
      intro y₁ y₂ hy₁ hy₂ h
      obtain ⟨x₁, f₁, _, rfl⟩ := exists_epi y₁ hy₁
      obtain ⟨x₂, f₂, _, rfl⟩ := exists_epi y₂ hy₂
      have h' : Y.map f₁.op x₁.1.1 = Y.map f₂.op x₂.1.1 := by
        rwa [← FunctorToTypes.comp, ← FunctorToTypes.comp, ιB_b, ιB_b,
          Subtype.ext_iff] at h
      obtain rfl : x₁ = x₂ := by
        rw [Subtype.ext_iff]
        exact Y.unique_nonDegenerate_simplex _ f₁ x₁.1 rfl f₂ x₂.1 h'
      obtain rfl : f₁ = f₂ :=
        Y.unique_nonDegenerate_map _ f₁ x₁.1 rfl f₂ x₁.1 h'
      rfl)⟩

end relativeCellComplexOfMono

open relativeCellComplexOfMono in
noncomputable def relativeCellComplexOfMono [Mono i] :
    RelativeCellComplex.{u} (basicCell := fun (n : ℕ) (_ : Unit) ↦ (boundary n).ι) i where
  F := (skeletonOfMono i).monotone.functor ⋙ Subcomplex.toPresheafFunctor
  isoBot := Subcomplex.isoOfEq (by simp) ≪≫ (asIso (toRangeSubcomplex i)).symm
  incl :=
    { app _ := Subcomplex.ι _
      naturality _ _ _ := rfl }
  isColimit := IsColimit.ofIsoColimit
      (isColimitOfPreserves Subcomplex.toPresheafFunctor
        ((CompleteLattice.colimitCocone
        ((skeletonOfMono i).monotone.functor)).isColimit))
          (Cocones.ext
            ((Subcomplex.isoOfEq (iSup_skeletonOfMono i)) ≪≫ Subcomplex.topIso Y)
        (fun _ ↦ by rfl))
  attachCells d hd :=
    { ι := ι i d
      π _ := ⟨⟩
      cofan₁ := _
      cofan₂ := _
      isColimit₁ := colimit.isColimit _
      isColimit₂ := colimit.isColimit _
      m := m i d
      hm := ιA_m
      g₁ := t i d
      g₂ := b i d
      isPushout := isPushout i d }

open relativeCellComplexOfMono in
lemma relativeCellComplexOfMono_attachCells_cell [Mono i] {d : ℕ} (s : ι i d) :
    ((relativeCellComplexOfMono i).attachCells d (by simp)).cell s = β s :=
  Sigma.ι_desc _ _

variable (X) in
noncomputable def relativeCellComplex :
    RelativeCellComplex.{u} (basicCell := fun (n : ℕ) (_ : Unit) ↦ (boundary n).ι)
      (Subcomplex.ι ⊥ : _ ⟶ X) :=
  relativeCellComplexOfMono _

variable (X) in
@[simps]
def relativeCellComplexCellsEquiv :
    (relativeCellComplex X).Cells ≃ X.N where
  toFun c := N.mk _ c.k.1.2
  invFun s :=
    { j := s.dim
      hj := by simp
      k := ⟨⟨_, s.nonDegenerate⟩, by simp ⟩ }
  left_inv _ := rfl
  right_inv _ := rfl

@[simp]
lemma relativeCellComplexι_eq (s : (relativeCellComplex X).Cells) :
    s.ι = yonedaEquiv.symm s.k.1.1 := by
  dsimp only [relativeCellComplex, RelativeCellComplex.Cells.ι] at s ⊢
  rw [relativeCellComplexOfMono_attachCells_cell]
  apply yonedaEquiv_symm_comp

namespace modelCategoryQuillen

open MorphismProperty

noncomputable def transfiniteCompositionOfMono {X Y : SSet.{u}} (i : X ⟶ Y) [Mono i] :
    (coproducts.{u} I).pushouts.TransfiniteCompositionOfShape ℕ i where
  toTransfiniteCompositionOfShape :=
    (relativeCellComplexOfMono i).toTransfiniteCompositionOfShape
  map_mem d hd := by
    apply pushouts_monotone _ _
      ((relativeCellComplexOfMono i).attachCells d hd).pushouts_coproducts
    apply coproducts_monotone
    rintro _ _ _ ⟨⟩
    exact boundary_ι_mem_I d

lemma transfiniteCompositions_pushouts_coproducts :
    transfiniteCompositions.{u} (coproducts.{u} I).pushouts = monomorphisms SSet.{u} := by
  apply le_antisymm
  · rw [transfiniteCompositions_le_iff, pushouts_le_iff, coproducts_le_iff]
    exact I_le_monomorphisms
  · intro _ _ i (_ : Mono i)
    apply transfiniteCompositionsOfShape_le_transfiniteCompositions _ (ULift ℕ)
    exact ⟨(transfiniteCompositionOfMono i).ofOrderIso (orderIsoULift.{u} ℕ).symm⟩

lemma I_rlp_eq_monomorphisms_rlp : I.{u}.rlp = (monomorphisms SSet.{u}).rlp := by
  apply le_antisymm
  · simp only [← transfiniteCompositions_pushouts_coproducts,
      rlp_transfiniteCompositions, rlp_pushouts, rlp_coproducts, le_refl]
  · exact MorphismProperty.antitone_rlp I_le_monomorphisms

end modelCategoryQuillen

end SSet
